EXTRA_CFLAGS += -DCONFIG_BMA_USE_PLATFORM_DATA

# EXTRA_CFLAGS += -DBMM_USE_BASIC_I2C_FUNC
# EXTRA_CFLAGS += -DCONFIG_BMM_USE_PLATFORM_DATA

obj-$(CONFIG_SENSORS_BMA2X2)	+= bma2x2_driver.o bst_sensor_common.o    
obj-$(CONFIG_SENSORS_BMC150)	+= bma2x2_driver.o bmm050_driver.o bmm050.o bst_sensor_common.o
