
obj-$(CONFIG_FB_SC8825) := sprdfb_main.o sprdfb_panel.o sprdfb_dispc.o sprdfb_lcdc.o sprdfb_mcu.o sprdfb_rgb.o sprdfb_mipi.o sprdfb_i2c.o sprdfb_spi.o sprdfb_dsi.o
obj-$(CONFIG_FB_SC8825) += dsi/
obj-$(CONFIG_FB_SC8825) += spi/



obj-$(CONFIG_FB_LCD_HX8362_RGB_SPI) += lcd_hx8362_rgb_spi.o
obj-$(CONFIG_FB_LCD_HX8369) += lcd_hx8369.o
obj-$(CONFIG_FB_LCD_S6D0139) += lcd_s6d0139.o
obj-$(CONFIG_FB_LCD_NT35516_MCU) += lcd_nt35516_mcu.o
obj-$(CONFIG_FB_LCD_NT35516_MIPI) += lcd_nt35516_mipi.o
obj-$(CONFIG_FB_LCD_NT35516_RGB_I2C) += lcd_nt35516_rgb_i2c.o
obj-$(CONFIG_FB_LCD_NT35516_RGB_SPI) += lcd_nt35516_rgb_spi.o
obj-$(CONFIG_FB_LCD_NT35510_MIPI) += lcd_nt35510_mipi.o
obj-$(CONFIG_FB_LCD_NT35512_MIPI) += lcd_nt35512_mipi.o
obj-$(CONFIG_FB_LCD_OTM8018B_MIPI) += lcd_otm_8018b_mipi.o
