# SPRD Platform Support
snd-soc-sprd-vbc-objs       := vbc.o
obj-$(CONFIG_SND_SPRD_SOC_VBC)       += snd-soc-sprd-vbc.o
snd-soc-sprd-vbc-pcm-objs       := sprd-vbc-pcm.o
obj-$(CONFIG_SND_SPRD_SOC_VBC)       += snd-soc-sprd-vbc-pcm.o
